# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtosvic_mandato_spesa_fissa_post import DTOSVICMandatoSpesaFissaPOST

class TestDTOSVICMandatoSpesaFissaPOST(unittest.TestCase):
    """DTOSVICMandatoSpesaFissaPOST unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOSVICMandatoSpesaFissaPOST:
        """Test DTOSVICMandatoSpesaFissaPOST
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOSVICMandatoSpesaFissaPOST`
        """
        model = DTOSVICMandatoSpesaFissaPOST()
        if include_optional:
            return DTOSVICMandatoSpesaFissaPOST(
                capitolo = '',
                articolo = '',
                causale = '',
                anno_pagamento = 56,
                anno_competenza = 56,
                dettaglio = [
                    openapi_client.models.dtosvic_riga_mandato.DTOSVICRigaMandato(
                        codice_creditore = '', 
                        importo = '', 
                        nota = '', )
                    ]
            )
        else:
            return DTOSVICMandatoSpesaFissaPOST(
        )
        """

    def testDTOSVICMandatoSpesaFissaPOST(self):
        """Test DTOSVICMandatoSpesaFissaPOST"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
