# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_richiesta_parametri import DTOAPIRichiestaParametri

class TestDTOAPIRichiestaParametri(unittest.TestCase):
    """DTOAPIRichiestaParametri unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPIRichiestaParametri:
        """Test DTOAPIRichiestaParametri
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPIRichiestaParametri`
        """
        model = DTOAPIRichiestaParametri()
        if include_optional:
            return DTOAPIRichiestaParametri(
                guid_prestazione = '',
                id_ultimo_parametro = 56,
                id_tipologia_dispositivo = 56,
                id_tipologia_dato = 56
            )
        else:
            return DTOAPIRichiestaParametri(
        )
        """

    def testDTOAPIRichiestaParametri(self):
        """Test DTOAPIRichiestaParametri"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
