# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_prodotto import DTOAPIProdotto

class TestDTOAPIProdotto(unittest.TestCase):
    """DTOAPIProdotto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPIProdotto:
        """Test DTOAPIProdotto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPIProdotto`
        """
        model = DTOAPIProdotto()
        if include_optional:
            return DTOAPIProdotto(
                nome_prodotto = '',
                categoria = openapi_client.models.dtoapi_categoria.DTOAPICategoria(
                    id = 56, )
            )
        else:
            return DTOAPIProdotto(
        )
        """

    def testDTOAPIProdotto(self):
        """Test DTOAPIProdotto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
