# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.svic_api import SVICApi


class TestSVICApi(unittest.TestCase):
    """SVICApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SVICApi()

    def tearDown(self) -> None:
        pass

    def test_s_vic_budget(self) -> None:
        """Test case for s_vic_budget

        """
        pass

    def test_s_vic_debitore(self) -> None:
        """Test case for s_vic_debitore

        """
        pass

    def test_s_vic_get_anagrafica(self) -> None:
        """Test case for s_vic_get_anagrafica

        """
        pass

    def test_s_vic_mandato(self) -> None:
        """Test case for s_vic_mandato

        """
        pass

    def test_s_vic_mandato_da_impegno(self) -> None:
        """Test case for s_vic_mandato_da_impegno

        """
        pass

    def test_s_vic_mandato_spesa_fissa(self) -> None:
        """Test case for s_vic_mandato_spesa_fissa

        """
        pass

    def test_s_vic_movimentazione(self) -> None:
        """Test case for s_vic_movimentazione

        """
        pass

    def test_s_vic_reversale(self) -> None:
        """Test case for s_vic_reversale

        """
        pass

    def test_s_vic_reversale1(self) -> None:
        """Test case for s_vic_reversale1

        """
        pass

    def test_s_vic_set_anagrafica(self) -> None:
        """Test case for s_vic_set_anagrafica

        """
        pass


if __name__ == '__main__':
    unittest.main()
