# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_consensi import DTOAPIConsensi

class TestDTOAPIConsensi(unittest.TestCase):
    """DTOAPIConsensi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPIConsensi:
        """Test DTOAPIConsensi
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPIConsensi`
        """
        model = DTOAPIConsensi()
        if include_optional:
            return DTOAPIConsensi(
                consenso = [
                    ''
                    ]
            )
        else:
            return DTOAPIConsensi(
        )
        """

    def testDTOAPIConsensi(self):
        """Test DTOAPIConsensi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
