# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_patologica_remota_interventi_pregressi import DTOPatologicaRemotaInterventiPregressi

class TestDTOPatologicaRemotaInterventiPregressi(unittest.TestCase):
    """DTOPatologicaRemotaInterventiPregressi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOPatologicaRemotaInterventiPregressi:
        """Test DTOPatologicaRemotaInterventiPregressi
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOPatologicaRemotaInterventiPregressi`
        """
        model = DTOPatologicaRemotaInterventiPregressi()
        if include_optional:
            return DTOPatologicaRemotaInterventiPregressi(
                nega_intervento = True,
                intervento = '',
                data_intervento = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                eta = 1.337,
                patologia = '',
                note = '',
                id_patologica_remota_interventi_pregressi = 56,
                id_assistito = 56,
                id_visita = 56
            )
        else:
            return DTOPatologicaRemotaInterventiPregressi(
        )
        """

    def testDTOPatologicaRemotaInterventiPregressi(self):
        """Test DTOPatologicaRemotaInterventiPregressi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
