# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_esami_strumentale import DTOAPIEsamiStrumentale

class TestDTOAPIEsamiStrumentale(unittest.TestCase):
    """DTOAPIEsamiStrumentale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPIEsamiStrumentale:
        """Test DTOAPIEsamiStrumentale
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPIEsamiStrumentale`
        """
        model = DTOAPIEsamiStrumentale()
        if include_optional:
            return DTOAPIEsamiStrumentale(
                esame_strumentale_conclusione = [
                    openapi_client.models.dto_esame_strumentale_conclusione_terapia.DTOEsameStrumentaleConclusioneTerapia(
                        id_conclusione_terapia = 56, 
                        id_assistito = 56, 
                        note_conclusioni = '', 
                        conclusioni = '', 
                        consigli_terapia = '', 
                        id_referto = 56, 
                        id_visita = 56, )
                    ]
            )
        else:
            return DTOAPIEsamiStrumentale(
        )
        """

    def testDTOAPIEsamiStrumentale(self):
        """Test DTOAPIEsamiStrumentale"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
