# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_account_add_external_login(self) -> None:
        """Test case for account_add_external_login

        Aggiunta di una servizio di login esterno
        """
        pass

    def test_account_change_password(self) -> None:
        """Test case for account_change_password

        Cambia la password utente
        """
        pass

    def test_account_get_external_login(self) -> None:
        """Test case for account_get_external_login

        Accesso tramite provider di terze parti
        """
        pass

    def test_account_get_external_logins(self) -> None:
        """Test case for account_get_external_logins

        Accesso tramite provider di terze parti
        """
        pass

    def test_account_get_manage_info(self) -> None:
        """Test case for account_get_manage_info

        Restituisce le informazioni di managment dell'utente
        """
        pass

    def test_account_get_user_info(self) -> None:
        """Test case for account_get_user_info

        Restituisce le informazioni dell'utente
        """
        pass

    def test_account_login(self) -> None:
        """Test case for account_login

        Login di uno specifico utente
        """
        pass

    def test_account_logout(self) -> None:
        """Test case for account_logout

        Disconnetti istanza
        """
        pass

    def test_account_register(self) -> None:
        """Test case for account_register

        Registra un nuovo utente per l'accesso al sistema
        """
        pass

    def test_account_register_external(self) -> None:
        """Test case for account_register_external

        Registers the external.
        """
        pass

    def test_account_remove_login(self) -> None:
        """Test case for account_remove_login

        Rimuovere una login esterna
        """
        pass

    def test_account_set_password(self) -> None:
        """Test case for account_set_password

        Imposta la password
        """
        pass


if __name__ == '__main__':
    unittest.main()
