# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.assistito_api import AssistitoApi


class TestAssistitoApi(unittest.TestCase):
    """AssistitoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssistitoApi()

    def tearDown(self) -> None:
        pass

    def test_assistito_lista(self) -> None:
        """Test case for assistito_lista

        """
        pass

    def test_assistito_scheda(self) -> None:
        """Test case for assistito_scheda

        """
        pass

    def test_assistito_somministrazioni(self) -> None:
        """Test case for assistito_somministrazioni

        """
        pass


if __name__ == '__main__':
    unittest.main()
