# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_visita import DTOAPIVisita

class TestDTOAPIVisita(unittest.TestCase):
    """DTOAPIVisita unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPIVisita:
        """Test DTOAPIVisita
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPIVisita`
        """
        model = DTOAPIVisita()
        if include_optional:
            return DTOAPIVisita(
                identificativo = '',
                data_intervento = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_invio = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                refertato = True,
                paziente = openapi_client.models.dtoapi_visita_paziente.DTOAPIVisitaPaziente(
                    id = 56, 
                    codice_fiscale = '', 
                    nome = '', 
                    cognome = '', 
                    data_nascita = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    comune_nascita = '', 
                    stato_coscienza = True, ),
                esami_ecg = [
                    openapi_client.models.dtoapi_visita_ecg.DTOAPIVisitaECG(
                        tipo_file = 56, 
                        path_file = '', )
                    ]
            )
        else:
            return DTOAPIVisita(
        )
        """

    def testDTOAPIVisita(self):
        """Test DTOAPIVisita"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
