# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtosvic_movimentazione import DTOSVICMovimentazione

class TestDTOSVICMovimentazione(unittest.TestCase):
    """DTOSVICMovimentazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOSVICMovimentazione:
        """Test DTOSVICMovimentazione
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOSVICMovimentazione`
        """
        model = DTOSVICMovimentazione()
        if include_optional:
            return DTOSVICMovimentazione(
                tipo_operazione = '',
                data_operazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                numero_operazione = 56,
                conto = 56,
                sottoconto = 56,
                dare_avere = '',
                importo = 56,
                missione = 56,
                descrizione_missione = '',
                programma = 56,
                descrizione_programma = '',
                titolo = 56,
                descrizione_titolo = '',
                responsabile = '',
                contro_di_costo_ricavo = ''
            )
        else:
            return DTOSVICMovimentazione(
        )
        """

    def testDTOSVICMovimentazione(self):
        """Test DTOSVICMovimentazione"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
