# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_device import DTOAPIDevice

class TestDTOAPIDevice(unittest.TestCase):
    """DTOAPIDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPIDevice:
        """Test DTOAPIDevice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPIDevice`
        """
        model = DTOAPIDevice()
        if include_optional:
            return DTOAPIDevice(
                guid_device = '',
                mac_address = '',
                api_key = '00000000-0000-0000-0000-000000000000',
                messaggio = '',
                stato = 56,
                licenza = openapi_client.models.dtoapi_licenza.DTOAPILicenza(
                    data_attivazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    tipologia_licenza = '', 
                    url_riferimento = '', 
                    api_key_licensed = '00000000-0000-0000-0000-000000000000', )
            )
        else:
            return DTOAPIDevice(
        )
        """

    def testDTOAPIDevice(self):
        """Test DTOAPIDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
