# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.attivita_domiciliare_api import AttivitaDomiciliareApi


class TestAttivitaDomiciliareApi(unittest.TestCase):
    """AttivitaDomiciliareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AttivitaDomiciliareApi()

    def tearDown(self) -> None:
        pass

    def test_attivita_domiciliare_interventi(self) -> None:
        """Test case for attivita_domiciliare_interventi

        Lista degli interventi con richiesta parametrizzata
        """
        pass

    def test_attivita_domiciliare_interventi1(self) -> None:
        """Test case for attivita_domiciliare_interventi1

        Lista degli interventi di un assistito
        """
        pass

    def test_attivita_domiciliare_interventi_assistito(self) -> None:
        """Test case for attivita_domiciliare_interventi_assistito

        Lista degli interventi di un assistito con richiesta parametrizzata
        """
        pass

    def test_attivita_domiciliare_prossimo_intervento(self) -> None:
        """Test case for attivita_domiciliare_prossimo_intervento

        Prossimo intervento.
        """
        pass

    def test_attivita_domiciliare_prossimo_intervento_assistito(self) -> None:
        """Test case for attivita_domiciliare_prossimo_intervento_assistito

        Prossimo intervento di un assistito.
        """
        pass


if __name__ == '__main__':
    unittest.main()
