# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.register_external_binding_model import RegisterExternalBindingModel

class TestRegisterExternalBindingModel(unittest.TestCase):
    """RegisterExternalBindingModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterExternalBindingModel:
        """Test RegisterExternalBindingModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterExternalBindingModel`
        """
        model = RegisterExternalBindingModel()
        if include_optional:
            return RegisterExternalBindingModel(
                email = ''
            )
        else:
            return RegisterExternalBindingModel(
                email = '',
        )
        """

    def testRegisterExternalBindingModel(self):
        """Test RegisterExternalBindingModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
