# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.prestazione_domiciliare_api import PrestazioneDomiciliareApi


class TestPrestazioneDomiciliareApi(unittest.TestCase):
    """PrestazioneDomiciliareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrestazioneDomiciliareApi()

    def tearDown(self) -> None:
        pass

    def test_prestazione_domiciliare_avvio_prestazione(self) -> None:
        """Test case for prestazione_domiciliare_avvio_prestazione

        Avvio di una prestazione domiciliare.
        """
        pass

    def test_prestazione_domiciliare_check_prestazione(self) -> None:
        """Test case for prestazione_domiciliare_check_prestazione

        Controllo della prestazione
        """
        pass

    def test_prestazione_domiciliare_interrompi_prestazione(self) -> None:
        """Test case for prestazione_domiciliare_interrompi_prestazione

        Interrompi la prestazione domiciliare.
        """
        pass

    def test_prestazione_domiciliare_invio_parametro(self) -> None:
        """Test case for prestazione_domiciliare_invio_parametro

        Salvataggio di un parametro rilevato
        """
        pass

    def test_prestazione_domiciliare_invio_set_parametri(self) -> None:
        """Test case for prestazione_domiciliare_invio_set_parametri

        Salvataggio di un set di parametri rilevato
        """
        pass

    def test_prestazione_domiciliare_parametri_rilevati(self) -> None:
        """Test case for prestazione_domiciliare_parametri_rilevati

        Elenco dei parametri di un intervento.
        """
        pass


if __name__ == '__main__':
    unittest.main()
