# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_modello_parziale import DTOModelloParziale

class TestDTOModelloParziale(unittest.TestCase):
    """DTOModelloParziale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOModelloParziale:
        """Test DTOModelloParziale
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOModelloParziale`
        """
        model = DTOModelloParziale()
        if include_optional:
            return DTOModelloParziale(
                time_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                time_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                settimana = [
                    True
                    ],
                gg_settimana = 56
            )
        else:
            return DTOModelloParziale(
        )
        """

    def testDTOModelloParziale(self):
        """Test DTOModelloParziale"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
