# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.somministrazione_api import SomministrazioneApi


class TestSomministrazioneApi(unittest.TestCase):
    """SomministrazioneApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SomministrazioneApi()

    def tearDown(self) -> None:
        pass

    def test_somministrazione_planning(self) -> None:
        """Test case for somministrazione_planning

        """
        pass


if __name__ == '__main__':
    unittest.main()
