# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_session import DTOAPISession

class TestDTOAPISession(unittest.TestCase):
    """DTOAPISession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPISession:
        """Test DTOAPISession
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPISession`
        """
        model = DTOAPISession()
        if include_optional:
            return DTOAPISession(
                guid_session = '00000000-0000-0000-0000-000000000000',
                utente = openapi_client.models.dtoapi_user.DTOAPIUser(
                    guid = '', 
                    user_name = '', 
                    email = '', 
                    password = '', 
                    tipologia = '', 
                    api_key = '00000000-0000-0000-0000-000000000000', 
                    nome = '', 
                    cognome = '', 
                    ruolo = '', 
                    id_tipologia = 56, 
                    codice_fiscale = '', 
                    guid_medibox = '', ),
                start_session = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expired = 56
            )
        else:
            return DTOAPISession(
        )
        """

    def testDTOAPISession(self):
        """Test DTOAPISession"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
