# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_esame_obiettivo_regionale import DTOEsameObiettivoRegionale

class TestDTOEsameObiettivoRegionale(unittest.TestCase):
    """DTOEsameObiettivoRegionale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOEsameObiettivoRegionale:
        """Test DTOEsameObiettivoRegionale
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOEsameObiettivoRegionale`
        """
        model = DTOEsameObiettivoRegionale()
        if include_optional:
            return DTOEsameObiettivoRegionale(
                id_assistito = 56,
                id_esame_obiettivo_regionale = 56,
                idmv_polmone_destro = '',
                idfvt_polmone_destro = '',
                id_percussione_polmone_destro = '',
                id_rumori_patologici_polmone_destro = '',
                id_sede_polmone_destro = '',
                idmv_polmone_sinistro = '',
                idfvt_polmone_sinistro = '',
                id_percussione_polmone_sinistro = '',
                id_rumori_patologici_polmone_sinistro = '',
                id_sede_polmone_sinistro = '',
                id_tono = '',
                id_soffi = '',
                id_apparato_urogenitale = '',
                id_addome = '',
                id_occhi = 56,
                id_vista = 56,
                note_vista = '',
                id_cavo_orale = 56,
                orecchio = '',
                id_udito = 56,
                note_udito = '',
                id_collo = 56,
                sistema_arterioso = '',
                sistema_venoso_linfatico = '',
                apparato_muscolo_scheletrico = '',
                alterazione_podologica = '',
                id_tono_sistema_nervoso = 56,
                note_tono_sistema_nervoso = '',
                id_movimenti = 56,
                id_visita = 56
            )
        else:
            return DTOEsameObiettivoRegionale(
        )
        """

    def testDTOEsameObiettivoRegionale(self):
        """Test DTOEsameObiettivoRegionale"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
