# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtosvic_anagrafica import DTOSVICAnagrafica

class TestDTOSVICAnagrafica(unittest.TestCase):
    """DTOSVICAnagrafica unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOSVICAnagrafica:
        """Test DTOSVICAnagrafica
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOSVICAnagrafica`
        """
        model = DTOSVICAnagrafica()
        if include_optional:
            return DTOSVICAnagrafica(
                cognome = '',
                nome = '',
                sesso = '',
                data_nascita = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                codice_istat_comune_nascita = '',
                codice_fiscale = '',
                indirizzo_residenza = '',
                codice_istat_comune_residenza = '',
                cap_residenza = '',
                telefono = '',
                cellulare = '',
                email = '',
                pec = ''
            )
        else:
            return DTOSVICAnagrafica(
        )
        """

    def testDTOSVICAnagrafica(self):
        """Test DTOSVICAnagrafica"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
