# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_esame_strumentale_conclusione_terapia import DTOEsameStrumentaleConclusioneTerapia

class TestDTOEsameStrumentaleConclusioneTerapia(unittest.TestCase):
    """DTOEsameStrumentaleConclusioneTerapia unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOEsameStrumentaleConclusioneTerapia:
        """Test DTOEsameStrumentaleConclusioneTerapia
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOEsameStrumentaleConclusioneTerapia`
        """
        model = DTOEsameStrumentaleConclusioneTerapia()
        if include_optional:
            return DTOEsameStrumentaleConclusioneTerapia(
                id_conclusione_terapia = 56,
                id_assistito = 56,
                note_conclusioni = '',
                conclusioni = '',
                consigli_terapia = '',
                id_referto = 56,
                id_visita = 56
            )
        else:
            return DTOEsameStrumentaleConclusioneTerapia(
        )
        """

    def testDTOEsameStrumentaleConclusioneTerapia(self):
        """Test DTOEsameStrumentaleConclusioneTerapia"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
