# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.documenti_api import DocumentiApi


class TestDocumentiApi(unittest.TestCase):
    """DocumentiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentiApi()

    def tearDown(self) -> None:
        pass

    def test_documenti_fattura(self) -> None:
        """Test case for documenti_fattura

        """
        pass

    def test_documenti_fatture(self) -> None:
        """Test case for documenti_fatture

        """
        pass


if __name__ == '__main__':
    unittest.main()
