# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.emergenza_api import EmergenzaApi


class TestEmergenzaApi(unittest.TestCase):
    """EmergenzaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmergenzaApi()

    def tearDown(self) -> None:
        pass

    def test_emergenza_crea_visita(self) -> None:
        """Test case for emergenza_crea_visita

        """
        pass


if __name__ == '__main__':
    unittest.main()
