# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_bisogni_paziente_alimentazione import DTOBisogniPazienteAlimentazione

class TestDTOBisogniPazienteAlimentazione(unittest.TestCase):
    """DTOBisogniPazienteAlimentazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOBisogniPazienteAlimentazione:
        """Test DTOBisogniPazienteAlimentazione
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOBisogniPazienteAlimentazione`
        """
        model = DTOBisogniPazienteAlimentazione()
        if include_optional:
            return DTOBisogniPazienteAlimentazione(
                assenza_alimentazione = True,
                alimentazione_orale = True,
                ausili_alimentazione = True,
                imboccato = True,
                dieta_specifica = True,
                dieta_sbilanciata = True,
                ematemesi = True,
                meteorismo = True,
                protesi_dentaria = True,
                nutrizione_parentale = True,
                nutrizione_enterale = True,
                melena = True,
                sondino = True,
                rifiuto_cibo = True,
                calo_ponderale = True,
                id_gastrectomia = 56,
                id_diabete = 56,
                intolleranze_alimentari = '',
                impedimento_alimentazione = '',
                note = '',
                id_analisi_bisogni_alimentazione = 56,
                id_assistito = 56,
                id_visita = 56
            )
        else:
            return DTOBisogniPazienteAlimentazione(
        )
        """

    def testDTOBisogniPazienteAlimentazione(self):
        """Test DTOBisogniPazienteAlimentazione"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
