# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtosvic_budget import DTOSVICBudget

class TestDTOSVICBudget(unittest.TestCase):
    """DTOSVICBudget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOSVICBudget:
        """Test DTOSVICBudget
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOSVICBudget`
        """
        model = DTOSVICBudget()
        if include_optional:
            return DTOSVICBudget(
                anno_budget = 56,
                mese_budget = 56,
                entrata_uscita = '',
                conto = 56,
                sottoconto = 56,
                descrizione = '',
                competenza = 56,
                cassa = 56,
                missione = 56,
                descrizione_missione = '',
                programma = 56,
                descrizione_programma = '',
                titolo = 56,
                descrizione_titolo = '',
                responsabile = '',
                contro_di_costo_ricavo = ''
            )
        else:
            return DTOSVICBudget(
        )
        """

    def testDTOSVICBudget(self):
        """Test DTOSVICBudget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
