# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtosvic_reversale_post import DTOSVICReversalePOST

class TestDTOSVICReversalePOST(unittest.TestCase):
    """DTOSVICReversalePOST unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOSVICReversalePOST:
        """Test DTOSVICReversalePOST
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOSVICReversalePOST`
        """
        model = DTOSVICReversalePOST()
        if include_optional:
            return DTOSVICReversalePOST(
                numero_accertamento = '',
                anno_pagamento = 56,
                anno_competenza = 56,
                dettaglio = [
                    openapi_client.models.dtosvic_riga_reversale.DTOSVICRigaReversale(
                        codice_debitore = '', 
                        importo = '', 
                        nota = '', )
                    ]
            )
        else:
            return DTOSVICReversalePOST(
        )
        """

    def testDTOSVICReversalePOST(self):
        """Test DTOSVICReversalePOST"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
