# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_licenza import DTOAPILicenza

class TestDTOAPILicenza(unittest.TestCase):
    """DTOAPILicenza unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPILicenza:
        """Test DTOAPILicenza
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPILicenza`
        """
        model = DTOAPILicenza()
        if include_optional:
            return DTOAPILicenza(
                data_attivazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tipologia_licenza = '',
                url_riferimento = '',
                api_key_licensed = '00000000-0000-0000-0000-000000000000'
            )
        else:
            return DTOAPILicenza(
        )
        """

    def testDTOAPILicenza(self):
        """Test DTOAPILicenza"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
