# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.archivio_parametri_api import ArchivioParametriApi


class TestArchivioParametriApi(unittest.TestCase):
    """ArchivioParametriApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArchivioParametriApi()

    def tearDown(self) -> None:
        pass

    def test_archivio_parametri_check_prestazione(self) -> None:
        """Test case for archivio_parametri_check_prestazione

        Controllo della prestazione
        """
        pass

    def test_archivio_parametri_crea_prestazione(self) -> None:
        """Test case for archivio_parametri_crea_prestazione

        Crea una prestazione.
        """
        pass

    def test_archivio_parametri_interrompi_prestazione(self) -> None:
        """Test case for archivio_parametri_interrompi_prestazione

        Interrompi la prestazione.
        """
        pass

    def test_archivio_parametri_invio_parametro(self) -> None:
        """Test case for archivio_parametri_invio_parametro

        Salvataggio di un parametro rilevato
        """
        pass

    def test_archivio_parametri_invio_set_parametri(self) -> None:
        """Test case for archivio_parametri_invio_set_parametri

        Salvataggio di un set di parametri rilevato
        """
        pass

    def test_archivio_parametri_parametri_rilevati(self) -> None:
        """Test case for archivio_parametri_parametri_rilevati

        Elenco dei parametri di un intervento.
        """
        pass


if __name__ == '__main__':
    unittest.main()
