# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_bisogni_paziente_eliminazione import DTOBisogniPazienteEliminazione

class TestDTOBisogniPazienteEliminazione(unittest.TestCase):
    """DTOBisogniPazienteEliminazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOBisogniPazienteEliminazione:
        """Test DTOBisogniPazienteEliminazione
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOBisogniPazienteEliminazione`
        """
        model = DTOBisogniPazienteEliminazione()
        if include_optional:
            return DTOBisogniPazienteEliminazione(
                ano_preternaturale = True,
                proctorragia = True,
                caterismo_intermittente = True,
                ritenzione_urinaria = True,
                catetere_vescicale = True,
                stipsi = True,
                dolori_addominali = True,
                tenesmo_rettale = True,
                drenaggio_transcutaneo = True,
                tenesmo_vescicale = True,
                ematuria = True,
                ureterostomie = True,
                id_incontinenza_fecale = 56,
                id_incontenenza_urinaria = 56,
                note = '',
                id_analisi_bisogni_eliminazione = 56,
                id_assistito = 56,
                id_visita = 56
            )
        else:
            return DTOBisogniPazienteEliminazione(
        )
        """

    def testDTOBisogniPazienteEliminazione(self):
        """Test DTOBisogniPazienteEliminazione"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
