# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtoapi_prestazione import DTOAPIPrestazione

class TestDTOAPIPrestazione(unittest.TestCase):
    """DTOAPIPrestazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOAPIPrestazione:
        """Test DTOAPIPrestazione
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOAPIPrestazione`
        """
        model = DTOAPIPrestazione()
        if include_optional:
            return DTOAPIPrestazione(
                id_prestazione_pai = 56,
                id_prestazione = 56,
                prestazione = '',
                descrizione = '',
                durata = 1.337
            )
        else:
            return DTOAPIPrestazione(
        )
        """

    def testDTOAPIPrestazione(self):
        """Test DTOAPIPrestazione"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
