# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_esame_obiettivo_generale import DTOEsameObiettivoGenerale

class TestDTOEsameObiettivoGenerale(unittest.TestCase):
    """DTOEsameObiettivoGenerale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOEsameObiettivoGenerale:
        """Test DTOEsameObiettivoGenerale
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOEsameObiettivoGenerale`
        """
        model = DTOEsameObiettivoGenerale()
        if include_optional:
            return DTOEsameObiettivoGenerale(
                data_visita = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                altezza = 1.337,
                peso = 1.337,
                bmi = 1.337,
                stato_nutrizione = '',
                circonferenza_addominale = 1.337,
                temperatura = 1.337,
                id_localizzazione_temperatura = 56,
                pa_sistolica = 1.337,
                pa_diastolica = 1.337,
                freq_respiro = 1.337,
                freq_cardiaca = 1.337,
                id_stato_generale = '',
                note = '',
                id_assistito = 56,
                id_esame_obiettivo_generale = 56,
                id_decubito = '',
                id_mucose = '',
                id_masse_muscolari = '',
                id_polso = '',
                id_stato_psichico = '',
                id_cute = '',
                id_sottocute = '',
                id_lingua = '',
                id_respiro = '',
                id_visita = 56
            )
        else:
            return DTOEsameObiettivoGenerale(
        )
        """

    def testDTOEsameObiettivoGenerale(self):
        """Test DTOEsameObiettivoGenerale"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
