# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_patologica_remota_ricoveri_pregressi import DTOPatologicaRemotaRicoveriPregressi

class TestDTOPatologicaRemotaRicoveriPregressi(unittest.TestCase):
    """DTOPatologicaRemotaRicoveriPregressi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOPatologicaRemotaRicoveriPregressi:
        """Test DTOPatologicaRemotaRicoveriPregressi
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOPatologicaRemotaRicoveriPregressi`
        """
        model = DTOPatologicaRemotaRicoveriPregressi()
        if include_optional:
            return DTOPatologicaRemotaRicoveriPregressi(
                data_ricovero = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                unita_ospedaliera = '',
                ospedale = '',
                id_patologica_remota_ricoveri_pregressi = 56,
                id_assistito = 56,
                id_visita = 56
            )
        else:
            return DTOPatologicaRemotaRicoveriPregressi(
        )
        """

    def testDTOPatologicaRemotaRicoveriPregressi(self):
        """Test DTOPatologicaRemotaRicoveriPregressi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
