# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.device_api import DeviceApi


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceApi()

    def tearDown(self) -> None:
        pass

    def test_device_licenza(self) -> None:
        """Test case for device_licenza

        """
        pass


if __name__ == '__main__':
    unittest.main()
