# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dto_bisogni_paziente_sicurezza_sonno import DTOBisogniPazienteSicurezzaSonno

class TestDTOBisogniPazienteSicurezzaSonno(unittest.TestCase):
    """DTOBisogniPazienteSicurezzaSonno unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOBisogniPazienteSicurezzaSonno:
        """Test DTOBisogniPazienteSicurezzaSonno
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOBisogniPazienteSicurezzaSonno`
        """
        model = DTOBisogniPazienteSicurezzaSonno()
        if include_optional:
            return DTOBisogniPazienteSicurezzaSonno(
                alterazione_sonno = True,
                allettato_con_sponde = True,
                rischio_infezione = True,
                insonnia = True,
                infezione_in_atto = True,
                agitazione = True,
                malattia_contagiosa = True,
                defedamento = True,
                sovrappeso = True,
                rischio_caduta = True,
                note = '',
                id_analisi_bisogni_sicurezza_sonno = 56,
                id_assistito = 56,
                id_visita = 56
            )
        else:
            return DTOBisogniPazienteSicurezzaSonno(
        )
        """

    def testDTOBisogniPazienteSicurezzaSonno(self):
        """Test DTOBisogniPazienteSicurezzaSonno"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
