# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dtosvic_riga_mandato import DTOSVICRigaMandato

class TestDTOSVICRigaMandato(unittest.TestCase):
    """DTOSVICRigaMandato unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DTOSVICRigaMandato:
        """Test DTOSVICRigaMandato
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DTOSVICRigaMandato`
        """
        model = DTOSVICRigaMandato()
        if include_optional:
            return DTOSVICRigaMandato(
                codice_creditore = '',
                importo = '',
                nota = ''
            )
        else:
            return DTOSVICRigaMandato(
        )
        """

    def testDTOSVICRigaMandato(self):
        """Test DTOSVICRigaMandato"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
