# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DTOPatologicaRemotaMalattie(BaseModel):
    """
    
    """ # noqa: E501
    diagnosi: Optional[StrictStr] = Field(default=None, description="Richiedi o modifica diagnosi.", alias="Diagnosi")
    id_stato_malattia: Optional[StrictInt] = Field(default=None, description="Richiedi o modifica identifier stato malattia.", alias="IDStatoMalattia")
    eta_malattia: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Richiedi o modifica eta malattia.", alias="EtaMalattia")
    note: Optional[StrictStr] = Field(default=None, description="Richiedi o modifica note.", alias="Note")
    id_patologica_remota_malattie: Optional[StrictInt] = Field(default=None, description="Richiedi o modifica identifier patologica remota malattie.", alias="IDPatologicaRemotaMalattie")
    id_assistito: Optional[StrictInt] = Field(default=None, description="Richiedi o modifica identifier assistito.", alias="IDAssistito")
    id_visita: Optional[StrictInt] = Field(default=None, alias="IDVisita")
    __properties: ClassVar[List[str]] = ["Diagnosi", "IDStatoMalattia", "EtaMalattia", "Note", "IDPatologicaRemotaMalattie", "IDAssistito", "IDVisita"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DTOPatologicaRemotaMalattie from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DTOPatologicaRemotaMalattie from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Diagnosi": obj.get("Diagnosi"),
            "IDStatoMalattia": obj.get("IDStatoMalattia"),
            "EtaMalattia": obj.get("EtaMalattia"),
            "Note": obj.get("Note"),
            "IDPatologicaRemotaMalattie": obj.get("IDPatologicaRemotaMalattie"),
            "IDAssistito": obj.get("IDAssistito"),
            "IDVisita": obj.get("IDVisita")
        })
        return _obj


