# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from openapi_client.models.dtoapi_visita_ecg import DTOAPIVisitaECG
from openapi_client.models.dtoapi_visita_paziente import DTOAPIVisitaPaziente
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DTOAPIVisita(BaseModel):
    """
    DTOAPIVisita
    """ # noqa: E501
    identificativo: Optional[StrictStr] = Field(default=None, alias="Identificativo")
    data_intervento: Optional[datetime] = Field(default=None, alias="DataIntervento")
    data_invio: Optional[datetime] = Field(default=None, alias="DataInvio")
    refertato: Optional[StrictBool] = Field(default=None, alias="Refertato")
    paziente: Optional[DTOAPIVisitaPaziente] = Field(default=None, alias="Paziente")
    esami_ecg: Optional[List[DTOAPIVisitaECG]] = Field(default=None, alias="EsamiECG")
    __properties: ClassVar[List[str]] = ["Identificativo", "DataIntervento", "DataInvio", "Refertato", "Paziente", "EsamiECG"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DTOAPIVisita from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of paziente
        if self.paziente:
            _dict['Paziente'] = self.paziente.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in esami_ecg (list)
        _items = []
        if self.esami_ecg:
            for _item in self.esami_ecg:
                if _item:
                    _items.append(_item.to_dict())
            _dict['EsamiECG'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DTOAPIVisita from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Identificativo": obj.get("Identificativo"),
            "DataIntervento": obj.get("DataIntervento"),
            "DataInvio": obj.get("DataInvio"),
            "Refertato": obj.get("Refertato"),
            "Paziente": DTOAPIVisitaPaziente.from_dict(obj.get("Paziente")) if obj.get("Paziente") is not None else None,
            "EsamiECG": [DTOAPIVisitaECG.from_dict(_item) for _item in obj.get("EsamiECG")] if obj.get("EsamiECG") is not None else None
        })
        return _obj


