# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.dtosvic_riga_mandato import DTOSVICRigaMandato
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DTOSVICMandatoImpegnoPOST(BaseModel):
    """
    DTOSVICMandatoImpegnoPOST
    """ # noqa: E501
    numero_impegno: Optional[StrictStr] = Field(default=None, alias="NumeroImpegno")
    anno_pagamento: Optional[StrictInt] = Field(default=None, alias="AnnoPagamento")
    anno_competenza: Optional[StrictInt] = Field(default=None, alias="AnnoCompetenza")
    anno_assunzione: Optional[StrictInt] = Field(default=None, alias="AnnoAssunzione")
    dettaglio: Optional[List[DTOSVICRigaMandato]] = Field(default=None, alias="Dettaglio")
    __properties: ClassVar[List[str]] = ["NumeroImpegno", "AnnoPagamento", "AnnoCompetenza", "AnnoAssunzione", "Dettaglio"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DTOSVICMandatoImpegnoPOST from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dettaglio (list)
        _items = []
        if self.dettaglio:
            for _item in self.dettaglio:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Dettaglio'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DTOSVICMandatoImpegnoPOST from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "NumeroImpegno": obj.get("NumeroImpegno"),
            "AnnoPagamento": obj.get("AnnoPagamento"),
            "AnnoCompetenza": obj.get("AnnoCompetenza"),
            "AnnoAssunzione": obj.get("AnnoAssunzione"),
            "Dettaglio": [DTOSVICRigaMandato.from_dict(_item) for _item in obj.get("Dettaglio")] if obj.get("Dettaglio") is not None else None
        })
        return _obj


