# coding: utf-8

"""
    MediHome-CloudServer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DTOSVICBudget(BaseModel):
    """
    DTOSVICBudget
    """ # noqa: E501
    anno_budget: Optional[StrictInt] = Field(default=None, alias="ANNO_BUDGET")
    mese_budget: Optional[StrictInt] = Field(default=None, alias="MESE_BUDGET")
    entrata_uscita: Optional[StrictStr] = Field(default=None, alias="ENTRATA_USCITA")
    conto: Optional[StrictInt] = Field(default=None, alias="CONTO")
    sottoconto: Optional[StrictInt] = Field(default=None, alias="SOTTOCONTO")
    descrizione: Optional[StrictStr] = Field(default=None, alias="DESCRIZIONE")
    competenza: Optional[StrictInt] = Field(default=None, alias="COMPETENZA")
    cassa: Optional[StrictInt] = Field(default=None, alias="CASSA")
    missione: Optional[StrictInt] = Field(default=None, alias="MISSIONE")
    descrizione_missione: Optional[StrictStr] = Field(default=None, alias="DESCRIZIONE_MISSIONE")
    programma: Optional[StrictInt] = Field(default=None, alias="PROGRAMMA")
    descrizione_programma: Optional[StrictStr] = Field(default=None, alias="DESCRIZIONE_PROGRAMMA")
    titolo: Optional[StrictInt] = Field(default=None, alias="TITOLO")
    descrizione_titolo: Optional[StrictStr] = Field(default=None, alias="DESCRIZIONE_TITOLO")
    responsabile: Optional[StrictStr] = Field(default=None, alias="RESPONSABILE")
    contro_di_costo_ricavo: Optional[StrictStr] = Field(default=None, alias="CONTRO_DI_COSTO_RICAVO")
    __properties: ClassVar[List[str]] = ["ANNO_BUDGET", "MESE_BUDGET", "ENTRATA_USCITA", "CONTO", "SOTTOCONTO", "DESCRIZIONE", "COMPETENZA", "CASSA", "MISSIONE", "DESCRIZIONE_MISSIONE", "PROGRAMMA", "DESCRIZIONE_PROGRAMMA", "TITOLO", "DESCRIZIONE_TITOLO", "RESPONSABILE", "CONTRO_DI_COSTO_RICAVO"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DTOSVICBudget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DTOSVICBudget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ANNO_BUDGET": obj.get("ANNO_BUDGET"),
            "MESE_BUDGET": obj.get("MESE_BUDGET"),
            "ENTRATA_USCITA": obj.get("ENTRATA_USCITA"),
            "CONTO": obj.get("CONTO"),
            "SOTTOCONTO": obj.get("SOTTOCONTO"),
            "DESCRIZIONE": obj.get("DESCRIZIONE"),
            "COMPETENZA": obj.get("COMPETENZA"),
            "CASSA": obj.get("CASSA"),
            "MISSIONE": obj.get("MISSIONE"),
            "DESCRIZIONE_MISSIONE": obj.get("DESCRIZIONE_MISSIONE"),
            "PROGRAMMA": obj.get("PROGRAMMA"),
            "DESCRIZIONE_PROGRAMMA": obj.get("DESCRIZIONE_PROGRAMMA"),
            "TITOLO": obj.get("TITOLO"),
            "DESCRIZIONE_TITOLO": obj.get("DESCRIZIONE_TITOLO"),
            "RESPONSABILE": obj.get("RESPONSABILE"),
            "CONTRO_DI_COSTO_RICAVO": obj.get("CONTRO_DI_COSTO_RICAVO")
        })
        return _obj


